"""项目常量。"""

from __future__ import annotations

APP_NAME = "agentic-workflow"
VERSION = "0.1.0"
CONFIG_DIR = ".agentic-workflow"
CONFIG_FILE = "config.json"
MANIFEST_FILE = "manifest.json"
DEFAULT_BRANCH = "main"
DEFAULT_RUNNER = "ubuntu-latest"
DEFAULT_LANGUAGE = "zh-CN"
WORKFLOW_VERSION = "2026.05"
GENERATED_MARK = "# Generated by agentic-workflow-installer"
